// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_Adminstatuschange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_Adminstatuschange));
        
        string IMigrationMetadata.Id
        {
            get { return "202304171204161_mig_Adminstatuschange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
